### ISSUE TITLE
Bug with License checker

### ISSUE THREAD

**Issue by hasansultan92** [hasansultan92/ECE461Part2#9]
1. If the RegEx expression comes true, without checking the license field it will return true for the license when the repo might not be licensed. For example it just checks if there is a "GNU" value in the package.json. If a "GNU" package is present it will detect and treat it as a license even though this is not necessarily true. 
2. if there is no license then it will return true.

**Comment by jasonbleasdell** [comment]
Possible fixes: first check to see if there "license" field. If not then return no license. If there is it then check the specific license object of what license it is

**Comment by jasonbleasdell** [comment]
Spent a few hours on this eventually I realized that their behavior is actually correct. It throws out invalid urls at the clone_and_install function call. Then if the github or npmjs repo doesn't have a valid license it will not have any of the appropriate packages and will throw it out with a 0 license score . If it does have a license, it will default is_valid to 1 and then it will loop through all of the dependences and check to make sure those dependences have correct licenses otherwise will set is_valid to 0 and return it.
